### PR TITLE
Make `InvalidArg` error more verbose

### LINKED ISSUE #14: Show argument causing error on InvalidArg
Figure out how to get getopts() to print the argument and handle it gracefully, instead of `expect()`-ing on the function call.

Here is an example of the output produced when compiling a project where cargo gives us some arguments we can't parse yet:

```sh
> $ cargo gccrs build
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.73
   Compiling serde_derive v1.0.126
   Compiling serde v1.0.126
   Compiling autocfg v1.0.1
   Compiling futures-core v0.3.15
   Compiling memchr v2.4.0
   Compiling libc v0.2.97
   Compiling proc-macro-hack v0.5.19
   Compiling futures-task v0.3.15
   Compiling futures-channel v0.3.15
   Compiling proc-macro-nested v0.1.7
   Compiling futures-io v0.3.15
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
error: could not compile `serde_derive`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: build failed
```

which is not helpful

### PR DESCRIPTION
**Pull request by CohenArthur**
Closes #14 

This PR makes `InvalidArg` errors clearer, which in turn will help development:

```sh
> cargo gccrs build
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg("Unrecognized option: \'cfg\'")', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'cannot translate rustc arguments into gccrs ones: InvalidArg("Unrecognized option: \'cap-lints\'")', src/main.rs:29:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### CODE REVIEW

**Review by flip1995 — APPROVED** [review]
Panicking to emit error messages is still bad style, but should be ok during development.

File: src/gccrs/error.rs [hunk 1]
```diff
@@ -8,7 +8,7 @@ use getopts::Fail;
 #[derive(Debug)]
 pub enum Error {
     /// Invalid argument given to `gccrs`
-    InvalidArg,
+    InvalidArg(String),
```
Comment (philberty) [inline src/gccrs/error.rs:11]: I wish i had enums like this in C++ lol

**Review by philberty — APPROVED** [review]
